FROM localhost/py_38

WORKDIR /app
CMD git clone https://github.com/C-RH-C/crhc-cli.git && \
    python3.8 -m venv ~/.venv/crhc-cli && \
    source ~/.venv/crhc-cli/bin/activate && \
    pip install --upgrade pip && \
    cd crhc-cli && \
    pip install -r requirements.txt && \
    chmod +x bin/crhc-cli && \
    bin/crhc-cli && \
    pyinstaller --paths=. --onefile bin/crhc-cli && \
    cp dist/crhc-cli /app/crhc-linux-x64
